import '@/styles/normalize.css'
import '@/styles/globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import TopNavigation from '@/components/Navigation/TopNavigation'
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Comrades',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavigation />
        <main className='px-4 max-w-[500px] mr-auto ml-auto pb-6 mt-[100px]'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
