export const cities = [
  'Jakarta',
  'Tangerang',
  'Bogor',
  'Bekasi',
  'Depok',
  'Bandung',
  'Semarang',
  'Jogja',
  'Solo',
  'Surabaya',
  'Medan',
  'Balikpapan',
  'Makasar',
  'Denpasar',
]

export const cityOptions = [
  { value: 'jakarta', label: 'Jakarta' },
  { value: 'tangerang', label: 'Tangerang' },
  { value: 'bogor', label: 'Bogor' },
  { value: 'bekasi', label: 'Bekasi' },
  { value: 'depok', label: 'Depok' },
  { value: 'bandung', label: 'Bandung' },
  { value: 'semarang', label: 'Semarang' },
  { value: 'surabaya', label: 'Surabaya' },
  { value: 'jogja', label: 'Jogja' },
  { value: 'solo', label: 'Solo' },
  { value: 'medan', label: 'Medan' },
  { value: 'balikpapan', label: 'Balikpapan' },
  { value: 'makasar', label: 'Makasar' },
  { value: 'denpasar', label: 'Denpasar' },
]
